version: "3"

services:
  web:
    build: .
    command: python manage.py runserver 0:8000
    env_file:
      - settings.env
    ports:
      - "8000:8000"
    volumes:
      - .:/web
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - ./db:/var/lib/postgresql/data
