# Generated by Django 3.1.4 on 2020-12-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curation', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('date', 'provider', 'menu')},
        ),
    ]
