# Generated by Django 3.1.4 on 2020-12-10 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201210_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.TextField(blank=True, editable=False, help_text='구주소')),
                ('new', models.TextField(blank=True, editable=False, help_text='신주소')),
                ('etc', models.TextField(blank=True, help_text='기타 주소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
