# Generated by Django 3.1.4 on 2020-12-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='new',
            field=models.TextField(blank=True, help_text='신주소'),
        ),
        migrations.AlterField(
            model_name='address',
            name='old',
            field=models.TextField(blank=True, help_text='구주소'),
        ),
    ]
