# Generated by Django 3.1.4 on 2020-12-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20201210_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(blank=True, help_text='우편번호', max_length=5),
        ),
    ]
