# Generated by Django 3.1.4 on 2020-12-11 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('NEW', '신규주문'), ('FOOD_ASSIGNMENT', '음식배정'), ('READY', '배송준비'), ('DELIVERING', '배송중'), ('DELIVERED', '배송완료')], default='NEW', max_length=100)),
                ('date', models.DateField()),
                ('new_address', models.TextField()),
                ('old_address', models.TextField()),
                ('zip', models.CharField(max_length=5)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.region')),
                ('stocks', models.ManyToManyField(to='inventory.Stock')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
