# Generated by Django 3.1.4 on 2020-12-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='etc_address',
            field=models.TextField(default=''),
        ),
    ]
