# Generated by Django 3.1.4 on 2020-12-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        ('order', '0002_order_etc_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.deliverer'),
        ),
    ]
