# Generated by Django 3.1.4 on 2020-12-11 18:24

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_deliverer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(choices=[('NEW', '신규주문'), ('FOOD_ASSIGNMENT', '음식배정'), ('READY', '배송준비'), ('DELIVERING', '배송중'), ('DELIVERED', '배송완료')], default='NEW', max_length=50),
        ),
    ]
